runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
runtime_config:
    python_version: 3
handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app
beta_settings:
  cloud_sql_instances: modified-hull-140217:us-central1:flask-demo
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10
env_variables:
  CLOUD_SQL_USERNAME: admin
  CLOUD_SQL_PASSWORD: t1ck1t
  CLOUD_SQL_DATABASE_NAME: tickitdb
  CLOUD_SQL_CONNECTION_NAME: modified-hull-140217:us-central1:flask-demo
  MODEL_BUCKET: tickit_values
  MODEL_FILENAME: serialized_model.json
  
